version: '3'
services:
  service-1:
    build:
      context: ./path/to/service-1
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - my-network

  service-2:
    build:
      context: ./path/to/service-2
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - my-network

networks:
  my-network:
